# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 390)
        MainWindow.setMinimumSize(QtCore.QSize(380, 390))
        MainWindow.setMaximumSize(QtCore.QSize(380, 390))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.apply = QtWidgets.QPushButton(self.centralwidget)
        self.apply.setEnabled(False)
        self.apply.setGeometry(QtCore.QRect(216, 352, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.apply.setFont(font)
        self.apply.setObjectName("apply")
        self.backup = QtWidgets.QPushButton(self.centralwidget)
        self.backup.setEnabled(False)
        self.backup.setGeometry(QtCore.QRect(6, 352, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.backup.setFont(font)
        self.backup.setObjectName("backup")
        self.path_button = QtWidgets.QPushButton(self.centralwidget)
        self.path_button.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.path_button.setFont(font)
        self.path_button.setObjectName("path_button")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 72, 361, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.basic_inf_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.basic_inf_layout.setContentsMargins(0, 0, 0, 0)
        self.basic_inf_layout.setObjectName("basic_inf_layout")
        self.money_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.money_lineedit.setObjectName("money_lineedit")
        self.basic_inf_layout.addWidget(self.money_lineedit, 0, 1, 1, 1)
        self.money_dont_change = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.money_dont_change.setObjectName("money_dont_change")
        self.basic_inf_layout.addWidget(self.money_dont_change, 0, 2, 1, 1)
        self.xp_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.xp_label.setFont(font)
        self.xp_label.setObjectName("xp_label")
        self.basic_inf_layout.addWidget(self.xp_label, 1, 0, 1, 1)
        self.xp_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.xp_lineedit.setObjectName("xp_lineedit")
        self.basic_inf_layout.addWidget(self.xp_lineedit, 1, 1, 1, 1)
        self.xp_dont_change = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.xp_dont_change.setObjectName("xp_dont_change")
        self.basic_inf_layout.addWidget(self.xp_dont_change, 1, 2, 1, 1)
        self.loan_limit_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.loan_limit_label.setFont(font)
        self.loan_limit_label.setObjectName("loan_limit_label")
        self.basic_inf_layout.addWidget(self.loan_limit_label, 2, 0, 1, 1)
        self.loan_limit_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.loan_limit_lineedit.setObjectName("loan_limit_lineedit")
        self.basic_inf_layout.addWidget(self.loan_limit_lineedit, 2, 1, 1, 1)
        self.loan_limit_dont_change = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.loan_limit_dont_change.setObjectName("loan_limit_dont_change")
        self.basic_inf_layout.addWidget(self.loan_limit_dont_change, 2, 2, 1, 1)
        self.money_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.money_label.setFont(font)
        self.money_label.setObjectName("money_label")
        self.basic_inf_layout.addWidget(self.money_label, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 160, 361, 161))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.skills_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.skills_layout.setContentsMargins(0, 0, 0, 0)
        self.skills_layout.setObjectName("skills_layout")
        self.long_distance_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.long_distance_lineedit.setObjectName("long_distance_lineedit")
        self.skills_layout.addWidget(self.long_distance_lineedit, 1, 1, 1, 1)
        self.urgent_delivery_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.urgent_delivery_label.setFont(font)
        self.urgent_delivery_label.setObjectName("urgent_delivery_label")
        self.skills_layout.addWidget(self.urgent_delivery_label, 4, 0, 1, 1)
        self.ecodriving_dont_change = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.ecodriving_dont_change.setObjectName("ecodriving_dont_change")
        self.skills_layout.addWidget(self.ecodriving_dont_change, 5, 2, 1, 1)
        self.adr_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.adr_lineedit.setObjectName("adr_lineedit")
        self.skills_layout.addWidget(self.adr_lineedit, 0, 1, 1, 1)
        self.urgent_delivery_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.urgent_delivery_lineedit.setObjectName("urgent_delivery_lineedit")
        self.skills_layout.addWidget(self.urgent_delivery_lineedit, 4, 1, 1, 1)
        self.fragile_cargo_dont_change = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.fragile_cargo_dont_change.setObjectName("fragile_cargo_dont_change")
        self.skills_layout.addWidget(self.fragile_cargo_dont_change, 3, 2, 1, 1)
        self.ecodriving_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.ecodriving_lineedit.setObjectName("ecodriving_lineedit")
        self.skills_layout.addWidget(self.ecodriving_lineedit, 5, 1, 1, 1)
        self.high_value_cargo_dont_change = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.high_value_cargo_dont_change.setObjectName("high_value_cargo_dont_change")
        self.skills_layout.addWidget(self.high_value_cargo_dont_change, 2, 2, 1, 1)
        self.fragile_cargo_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.fragile_cargo_lineedit.setObjectName("fragile_cargo_lineedit")
        self.skills_layout.addWidget(self.fragile_cargo_lineedit, 3, 1, 1, 1)
        self.adr_dont_change = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.adr_dont_change.setObjectName("adr_dont_change")
        self.skills_layout.addWidget(self.adr_dont_change, 0, 2, 1, 1)
        self.long_distance_dont_change = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.long_distance_dont_change.setObjectName("long_distance_dont_change")
        self.skills_layout.addWidget(self.long_distance_dont_change, 1, 2, 1, 1)
        self.high_value_cargo_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.high_value_cargo_lineedit.setObjectName("high_value_cargo_lineedit")
        self.skills_layout.addWidget(self.high_value_cargo_lineedit, 2, 1, 1, 1)
        self.high_value_cargo_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.high_value_cargo_label.setFont(font)
        self.high_value_cargo_label.setObjectName("high_value_cargo_label")
        self.skills_layout.addWidget(self.high_value_cargo_label, 2, 0, 1, 1)
        self.fragile_cargo_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.fragile_cargo_label.setFont(font)
        self.fragile_cargo_label.setObjectName("fragile_cargo_label")
        self.skills_layout.addWidget(self.fragile_cargo_label, 3, 0, 1, 1)
        self.ecodriving_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.ecodriving_label.setFont(font)
        self.ecodriving_label.setObjectName("ecodriving_label")
        self.skills_layout.addWidget(self.ecodriving_label, 5, 0, 1, 1)
        self.urgent_delivery_dont_change = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.urgent_delivery_dont_change.setObjectName("urgent_delivery_dont_change")
        self.skills_layout.addWidget(self.urgent_delivery_dont_change, 4, 2, 1, 1)
        self.long_distance_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.long_distance_label.setFont(font)
        self.long_distance_label.setObjectName("long_distance_label")
        self.skills_layout.addWidget(self.long_distance_label, 1, 0, 1, 1)
        self.adr_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.adr_label.setFont(font)
        self.adr_label.setObjectName("adr_label")
        self.skills_layout.addWidget(self.adr_label, 0, 0, 1, 1)
        self.second_window = QtWidgets.QToolButton(self.centralwidget)
        self.second_window.setEnabled(False)
        self.second_window.setGeometry(QtCore.QRect(170, 360, 31, 21))
        self.second_window.setObjectName("second_window")
        self.owns_sc = QtWidgets.QCheckBox(self.centralwidget)
        self.owns_sc.setEnabled(False)
        self.owns_sc.setGeometry(QtCore.QRect(0, 50, 131, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.owns_sc.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.owns_sc.setFont(font)
        self.owns_sc.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.owns_sc.setObjectName("owns_sc")
        self.owns_fr = QtWidgets.QCheckBox(self.centralwidget)
        self.owns_fr.setEnabled(False)
        self.owns_fr.setGeometry(QtCore.QRect(160, 50, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.owns_fr.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.owns_fr.setFont(font)
        self.owns_fr.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.owns_fr.setCheckable(True)
        self.owns_fr.setObjectName("owns_fr")
        self.owns_it = QtWidgets.QCheckBox(self.centralwidget)
        self.owns_it.setEnabled(False)
        self.owns_it.setGeometry(QtCore.QRect(280, 50, 91, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.owns_it.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.owns_it.setFont(font)
        self.owns_it.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.owns_it.setCheckable(True)
        self.owns_it.setObjectName("owns_it")
        self.dont_change_all_inf = QtWidgets.QCheckBox(self.centralwidget)
        self.dont_change_all_inf.setGeometry(QtCore.QRect(110, 325, 181, 20))
        self.dont_change_all_inf.setObjectName("dont_change_all_inf")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SaveWizard"))
        self.apply.setText(_translate("MainWindow", "Apply changes"))
        self.backup.setText(_translate("MainWindow", "Recover backup"))
        self.path_button.setText(_translate("MainWindow", "Choose save file..."))
        self.money_dont_change.setText(_translate("MainWindow", "Don\'t change"))
        self.xp_label.setText(_translate("MainWindow", "Experience:"))
        self.xp_dont_change.setText(_translate("MainWindow", "Don\'t change"))
        self.loan_limit_label.setText(_translate("MainWindow", "Loan limit:"))
        self.loan_limit_dont_change.setText(_translate("MainWindow", "Don\'t change"))
        self.money_label.setText(_translate("MainWindow", "Money:"))
        self.urgent_delivery_label.setText(_translate("MainWindow", "Urgent delivery:"))
        self.ecodriving_dont_change.setText(_translate("MainWindow", "Don\'t change"))
        self.fragile_cargo_dont_change.setText(_translate("MainWindow", "Don\'t change"))
        self.high_value_cargo_dont_change.setText(_translate("MainWindow", "Don\'t change"))
        self.adr_dont_change.setText(_translate("MainWindow", "Don\'t change"))
        self.long_distance_dont_change.setText(_translate("MainWindow", "Don\'t change"))
        self.high_value_cargo_label.setText(_translate("MainWindow", "High value cargo:"))
        self.fragile_cargo_label.setText(_translate("MainWindow", "Fragile cargo:"))
        self.ecodriving_label.setText(_translate("MainWindow", "Ecodriving:"))
        self.urgent_delivery_dont_change.setText(_translate("MainWindow", "Don\'t change"))
        self.long_distance_label.setText(_translate("MainWindow", "Long distance:"))
        self.adr_label.setText(_translate("MainWindow", "ADR:"))
        self.second_window.setText(_translate("MainWindow", "..."))
        self.owns_sc.setText(_translate("MainWindow", "Owns Scandinavia?"))
        self.owns_fr.setText(_translate("MainWindow", "Owns France?"))
        self.owns_it.setText(_translate("MainWindow", "Owns Italia?"))
        self.dont_change_all_inf.setText(_translate("MainWindow", "Don\'t save all changes in this form"))

