# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second_form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.setMinimumSize(QtCore.QSize(660, 400))
        SecondWindow.setMaximumSize(QtCore.QSize(660, 400))
        self.gridLayoutWidget_4 = QtWidgets.QWidget(SecondWindow)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 131, 191))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.garages_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.garages_layout.setContentsMargins(0, 0, 0, 0)
        self.garages_layout.setObjectName("garages_layout")
        self.garages_text = QtWidgets.QTextBrowser(self.gridLayoutWidget_4)
        self.garages_text.setOpenLinks(False)
        self.garages_text.setObjectName("garages_text")
        self.garages_layout.addWidget(self.garages_text, 1, 0, 1, 1)
        self.garages_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.garages_label.setFont(font)
        self.garages_label.setObjectName("garages_label")
        self.garages_layout.addWidget(self.garages_label, 0, 0, 1, 1)
        self.garages_analyze = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.garages_analyze.setFont(font)
        self.garages_analyze.setObjectName("garages_analyze")
        self.garages_layout.addWidget(self.garages_analyze, 2, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(SecondWindow)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(340, 10, 131, 191))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.cities_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.cities_layout.setContentsMargins(0, 0, 0, 0)
        self.cities_layout.setObjectName("cities_layout")
        self.cities_text = QtWidgets.QTextBrowser(self.gridLayoutWidget_5)
        self.cities_text.setOpenLinks(False)
        self.cities_text.setObjectName("cities_text")
        self.cities_layout.addWidget(self.cities_text, 1, 0, 1, 1)
        self.cities_analyze = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.cities_analyze.setFont(font)
        self.cities_analyze.setObjectName("cities_analyze")
        self.cities_layout.addWidget(self.cities_analyze, 2, 0, 1, 1)
        self.cities_visited_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.cities_visited_label.setFont(font)
        self.cities_visited_label.setObjectName("cities_visited_label")
        self.cities_layout.addWidget(self.cities_visited_label, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(SecondWindow)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 220, 131, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.dealerships_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.dealerships_layout.setContentsMargins(0, 0, 0, 0)
        self.dealerships_layout.setObjectName("dealerships_layout")
        self.dealerships_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.dealerships_label.setFont(font)
        self.dealerships_label.setObjectName("dealerships_label")
        self.dealerships_layout.addWidget(self.dealerships_label, 0, 0, 1, 1)
        self.dealerships_text = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.dealerships_text.setObjectName("dealerships_text")
        self.dealerships_layout.addWidget(self.dealerships_text, 1, 0, 1, 1)
        self.dealerships_analyze = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.dealerships_analyze.setFont(font)
        self.dealerships_analyze.setObjectName("dealerships_analyze")
        self.dealerships_layout.addWidget(self.dealerships_analyze, 2, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(SecondWindow)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(340, 220, 131, 171))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.agencies_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.agencies_layout.setContentsMargins(0, 0, 0, 0)
        self.agencies_layout.setObjectName("agencies_layout")
        self.agencies_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.agencies_label.setFont(font)
        self.agencies_label.setObjectName("agencies_label")
        self.agencies_layout.addWidget(self.agencies_label, 0, 0, 1, 1)
        self.agencies_text = QtWidgets.QTextBrowser(self.gridLayoutWidget_6)
        self.agencies_text.setObjectName("agencies_text")
        self.agencies_layout.addWidget(self.agencies_text, 1, 0, 1, 1)
        self.agencies_analyze = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.agencies_analyze.setFont(font)
        self.agencies_analyze.setObjectName("agencies_analyze")
        self.agencies_layout.addWidget(self.agencies_analyze, 2, 0, 1, 1)
        self.v_line = QtWidgets.QFrame(SecondWindow)
        self.v_line.setGeometry(QtCore.QRect(320, 10, 20, 381))
        self.v_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line.setObjectName("v_line")
        self.h_line = QtWidgets.QFrame(SecondWindow)
        self.h_line.setGeometry(QtCore.QRect(10, 200, 641, 16))
        self.h_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line.setObjectName("h_line")
        self.gridLayoutWidget = QtWidgets.QWidget(SecondWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(150, 10, 171, 107))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.add_garage = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.add_garage.setContentsMargins(0, 0, 0, 0)
        self.add_garage.setObjectName("add_garage")
        self.garage_add = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.garage_add.setFont(font)
        self.garage_add.setObjectName("garage_add")
        self.add_garage.addWidget(self.garage_add, 2, 0, 1, 1)
        self.garage_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.garage_lineedit.setObjectName("garage_lineedit")
        self.add_garage.addWidget(self.garage_lineedit, 1, 0, 1, 1)
        self.garage_unlock_all = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.garage_unlock_all.setFont(font)
        self.garage_unlock_all.setObjectName("garage_unlock_all")
        self.add_garage.addWidget(self.garage_unlock_all, 3, 0, 1, 1)
        self.garage_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.garage_label.setFont(font)
        self.garage_label.setObjectName("garage_label")
        self.add_garage.addWidget(self.garage_label, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(SecondWindow)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(480, 50, 171, 107))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.add_city = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.add_city.setContentsMargins(0, 0, 0, 0)
        self.add_city.setObjectName("add_city")
        self.city_add = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.city_add.setFont(font)
        self.city_add.setObjectName("city_add")
        self.add_city.addWidget(self.city_add, 2, 0, 1, 1)
        self.city_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.city_lineedit.setObjectName("city_lineedit")
        self.add_city.addWidget(self.city_lineedit, 1, 0, 1, 1)
        self.city_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.city_label.setFont(font)
        self.city_label.setObjectName("city_label")
        self.add_city.addWidget(self.city_label, 0, 0, 1, 1)
        self.city_unlock_all = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.city_unlock_all.setFont(font)
        self.city_unlock_all.setObjectName("city_unlock_all")
        self.add_city.addWidget(self.city_unlock_all, 3, 0, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(SecondWindow)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(150, 250, 171, 107))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.add_dealership = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.add_dealership.setContentsMargins(0, 0, 0, 0)
        self.add_dealership.setObjectName("add_dealership")
        self.dealership_add = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.dealership_add.setFont(font)
        self.dealership_add.setObjectName("dealership_add")
        self.add_dealership.addWidget(self.dealership_add, 2, 0, 1, 1)
        self.dealership_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.dealership_lineedit.setObjectName("dealership_lineedit")
        self.add_dealership.addWidget(self.dealership_lineedit, 1, 0, 1, 1)
        self.dealership_label = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.dealership_label.setFont(font)
        self.dealership_label.setObjectName("dealership_label")
        self.add_dealership.addWidget(self.dealership_label, 0, 0, 1, 1)
        self.dealership_unlock_all = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.dealership_unlock_all.setFont(font)
        self.dealership_unlock_all.setObjectName("dealership_unlock_all")
        self.add_dealership.addWidget(self.dealership_unlock_all, 3, 0, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(SecondWindow)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(480, 250, 171, 107))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.add_agency = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.add_agency.setContentsMargins(0, 0, 0, 0)
        self.add_agency.setObjectName("add_agency")
        self.agency_add = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.agency_add.setFont(font)
        self.agency_add.setObjectName("agency_add")
        self.add_agency.addWidget(self.agency_add, 2, 0, 1, 1)
        self.agency_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.agency_lineedit.setObjectName("agency_lineedit")
        self.add_agency.addWidget(self.agency_lineedit, 1, 0, 1, 1)
        self.agency_label = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.agency_label.setFont(font)
        self.agency_label.setObjectName("agency_label")
        self.add_agency.addWidget(self.agency_label, 0, 0, 1, 1)
        self.agency_unlock_all = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.agency_unlock_all.setFont(font)
        self.agency_unlock_all.setObjectName("agency_unlock_all")
        self.add_agency.addWidget(self.agency_unlock_all, 3, 0, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(SecondWindow)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(150, 120, 171, 80))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.headquarter_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.headquarter_layout.setContentsMargins(0, 0, 0, 0)
        self.headquarter_layout.setObjectName("headquarter_layout")
        self.headquarter_label = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.headquarter_label.setFont(font)
        self.headquarter_label.setObjectName("headquarter_label")
        self.headquarter_layout.addWidget(self.headquarter_label, 0, 0, 1, 1)
        self.headquarter_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.headquarter_lineedit.setObjectName("headquarter_lineedit")
        self.headquarter_layout.addWidget(self.headquarter_lineedit, 1, 0, 1, 1)
        self.headquarter_change = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.headquarter_change.setFont(font)
        self.headquarter_change.setObjectName("headquarter_change")
        self.headquarter_layout.addWidget(self.headquarter_change, 2, 0, 1, 1)
        self.gridLayoutWidget_4.raise_()
        self.gridLayoutWidget_5.raise_()
        self.gridLayoutWidget_2.raise_()
        self.gridLayoutWidget_6.raise_()
        self.v_line.raise_()
        self.h_line.raise_()
        self.gridLayoutWidget.raise_()
        self.gridLayoutWidget_3.raise_()
        self.gridLayoutWidget_7.raise_()
        self.gridLayoutWidget_8.raise_()
        self.garage_label.raise_()
        self.gridLayoutWidget_9.raise_()

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "Edit garages, cities and etc..."))
        self.garages_label.setText(_translate("SecondWindow", "Owned garages:"))
        self.garages_analyze.setText(_translate("SecondWindow", "Analyze"))
        self.cities_analyze.setText(_translate("SecondWindow", "Analyze"))
        self.cities_visited_label.setText(_translate("SecondWindow", "Visited cities:"))
        self.dealerships_label.setText(_translate("SecondWindow", "Dealerships:"))
        self.dealerships_analyze.setText(_translate("SecondWindow", "Analyze"))
        self.agencies_label.setText(_translate("SecondWindow", "Agencies:"))
        self.agencies_analyze.setText(_translate("SecondWindow", "Analyze"))
        self.garage_add.setText(_translate("SecondWindow", "Add"))
        self.garage_unlock_all.setText(_translate("SecondWindow", "Unlock all"))
        self.garage_label.setText(_translate("SecondWindow", "Enter garage name:"))
        self.city_add.setText(_translate("SecondWindow", "Add"))
        self.city_label.setText(_translate("SecondWindow", "Enter city name:"))
        self.city_unlock_all.setText(_translate("SecondWindow", "Visit all"))
        self.dealership_add.setText(_translate("SecondWindow", "Add"))
        self.dealership_label.setText(_translate("SecondWindow", "Enter dealership name:"))
        self.dealership_unlock_all.setText(_translate("SecondWindow", "Unlock all"))
        self.agency_add.setText(_translate("SecondWindow", "Add"))
        self.agency_label.setText(_translate("SecondWindow", "Enter agency name:"))
        self.agency_unlock_all.setText(_translate("SecondWindow", "Unlock all"))
        self.headquarter_label.setText(_translate("SecondWindow", "Your headquarter:"))
        self.headquarter_change.setText(_translate("SecondWindow", "Change"))

